FROM golang:1.17 as builder
WORKDIR /app
COPY producer/go.mod ./
RUN go mod download
COPY producer/ .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o producer .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/producer .
CMD ["./producer"]
