FROM bitnami/spark:latest

USER root

RUN apt update && \
    apt install -y python3-pip && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /opt/spark-apps/
RUN pip3 install --no-cache-dir -r /opt/spark-apps/requirements.txt

COPY spark_streaming_job_emojis.py /opt/spark-apps/

CMD /opt/bitnami/spark/bin/spark-submit \
    --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1 \
    /opt/spark-apps/spark_streaming_job_emojis.py
