FROM golang:1.17 as builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o message-service .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/message-service .
COPY kafka-config.json ./
# COPY dummy-server.crt dummy-server.key dummy-server.csr ./
CMD ["./message-service"]
