FROM golang:1.17 as builder
WORKDIR /app
COPY consumer/go.mod ./
RUN go mod download
COPY consumer/ .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o consumer .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/consumer .
CMD ["./consumer"]
